// examples/02-react-vite/App.tsx
import React, { useEffect, useRef } from "react";
import { WebDrive } from "webdrive";
import "webdrive/styles.css";

export default function App() {
  const tourRef = useRef<WebDrive | null>(null);

  useEffect(() => {
    tourRef.current = new WebDrive({
      id: "react-vite-tour",
      steps: [
        {
          element: "#vite-header",
          title: "Vite + React Integration",
          description: "Declarative UI tours in modern React 18+ applications.",
          position: "bottom",
        },
        {
          element: "#vite-counter",
          title: "Interactive State",
          description: "WebDrive highlights elements cleanly during React re-renders.",
          position: "top",
        },
      ],
      showProgress: true,
      animate: true,
    });

    return () => {
      tourRef.current?.destroy();
    };
  }, []);

  const [count, setCount] = React.useState(0);

  return (
    <div style={{ fontFamily: "sans-serif", padding: "40px", maxWidth: "600px", margin: "auto" }}>
      <header id="vite-header">
        <h1>React + Vite WebDrive Example</h1>
        <p>Framework-agnostic tour library in React.</p>
      </header>

      <div style={{ marginTop: "30px", display: "flex", gap: "12px" }}>
        <button
          onClick={() => tourRef.current?.start()}
          style={{ padding: "10px 16px", background: "#2563eb", color: "#fff", border: "none", borderRadius: "6px", cursor: "pointer" }}
        >
          Start React Tour
        </button>

        <button
          id="vite-counter"
          onClick={() => setCount((c) => c + 1)}
          style={{ padding: "10px 16px", border: "1px solid #ccc", background: "#fff", borderRadius: "6px", cursor: "pointer" }}
        >
          Count is {count}
        </button>
      </div>
    </div>
  );
}

// examples/03-vue-composition/App.vue
<script setup lang="ts">
import { useTour } from "./useTour";
import "webdrive/styles.css";

const { start, isActive } = useTour({
  id: "vue-demo-tour",
  steps: [
    {
      element: "#vue-banner",
      title: "Vue 3 Integration",
      description: "Seamless product walkthroughs powered by Vue 3 Composition API.",
      position: "bottom"
    },
    {
      element: "#vue-card",
      title: "Reactive State",
      description: "WebDrive highlights elements cleanly across Vue reactivity.",
      position: "top"
    }
  ]
});
</script>

<template>
  <div style="font-family: sans-serif; padding: 40px; max-width: 600px; margin: auto;">
    <header id="vue-banner">
      <h1>Vue 3 Composition API Showcase</h1>
      <p>Framework-agnostic tours in Vue 3.</p>
    </header>

    <div id="vue-card" style="margin-top: 30px; border: 1px solid #ddd; padding: 20px; border-radius: 8px;">
      <p>This is a reactive Vue component card.</p>
      <button
        @click="start(0)"
        :disabled="isActive"
        style="padding: 8px 16px; background: #42b883; color: #fff; border: none; border-radius: 4px; cursor: pointer;"
      >
        Launch Vue Tour
      </button>
    </div>
  </div>
</template>
